# Generated by Django 6.1 on 2026-08-08 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QCM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('est_public', models.BooleanField(default=False)),
                ('duree_minutes', models.PositiveIntegerField(help_text='Durée globale du QCM en minutes')),
                ('tentatives_autorisees', models.PositiveIntegerField(default=1, help_text='0 = illimité')),
                ('mode_scoring_choix_multiple', models.CharField(choices=[('tout_ou_rien', 'Tout ou rien'), ('points_partiels', 'Points partiels')], default='tout_ou_rien', max_length=20)),
                ('affichage_score', models.CharField(choices=[('immediat_partiel', 'Immédiat (partiel si texte libre)'), ('masque', "Masqué jusqu'à correction complète")], default='immediat_partiel', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_publication', models.DateTimeField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('createur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qcms_crees', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qcms', to='core.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enonce', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/images/')),
                ('type_question', models.CharField(choices=[('choix_unique', 'Choix unique (radio)'), ('choix_multiple', 'Choix multiple (checkbox)'), ('texte_libre', 'Texte libre')], max_length=20)),
                ('points', models.PositiveIntegerField(default=1, help_text='Poids / difficulté')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('qcm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='qcm.qcm')),
            ],
        ),
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=500)),
                ('est_correcte', models.BooleanField(default=False)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='qcm.question')),
            ],
        ),
        migrations.CreateModel(
            name='Thematique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thematiques', to='core.organisation')),
            ],
        ),
        migrations.AddField(
            model_name='qcm',
            name='thematique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qcms', to='qcm.thematique'),
        ),
    ]
