# Generated by Django 5.1.15 on 2026-08-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qcm',
            name='penalise_erreurs_choix_multiple',
            field=models.BooleanField(default=False, help_text='Si activé, chaque mauvaise réponse cochée retire des points (mode points_partiels uniquement)'),
        ),
    ]
