# Generated by Django 5.1.15 on 2026-08-10 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_groupeorganisation'),
        ('qcm', '0002_qcm_penalise_erreurs_choix_multiple'),
    ]

    operations = [
        migrations.AddField(
            model_name='qcm',
            name='groupes',
            field=models.ManyToManyField(blank=True, help_text="Si aucun groupe n'est sélectionné, le QCM est visible par toute l'organisation.", related_name='qcms', to='core.groupeorganisation'),
        ),
    ]
