# Generated by Django 5.1.15 on 2026-08-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametrePlateforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quota_qcm_gratuit_par_jour', models.PositiveIntegerField(default=10, help_text="Nombre de QCM qu'un individuel sans abonnement/pack peut passer gratuitement par jour.")),
            ],
        ),
    ]
