# Generated by Django 5.1.15 on 2026-08-10 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_parametreplateforme'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupeOrganisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('membres', models.ManyToManyField(blank=True, related_name='groupes', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupes', to='core.organisation')),
            ],
        ),
    ]
