# Generated by Django 5.1.15 on 2026-08-26 15:16

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_groupeorganisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='couleur_primaire',
            field=models.CharField(default='#16233F', max_length=7),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='couleur_secondaire',
            field=models.CharField(default='#D9A441', max_length=7),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='logo',
            field=models.ImageField(blank=True, help_text='Formats acceptés : JPG, PNG, WEBP — 2 Mo maximum.', null=True, upload_to='organisations/logos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), core.validators.valider_taille_image, core.validators.valider_contenu_image]),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
