# Generated by Django 5.1.15 on 2026-08-17 09:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('abonnements', '0002_pack_achatpack'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_interne', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('devise', models.CharField(default='XOF', max_length=10)),
                ('mode', models.CharField(choices=[('mobile_money', 'Mobile Money'), ('cash', 'Cash (validation manuelle)')], max_length=20)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('refuse', 'Refusé'), ('rembourse', 'Remboursé')], default='en_attente', max_length=20)),
                ('fournisseur', models.CharField(blank=True, help_text='ex: cinetpay, paydunya, simulateur', max_length=30)),
                ('reference_transaction', models.CharField(blank=True, max_length=255, null=True)),
                ('url_redirection', models.URLField(blank=True, null=True)),
                ('reponse_fournisseur', models.JSONField(blank=True, null=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('abonnement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='abonnements.abonnement')),
                ('achat_pack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='abonnements.achatpack')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to=settings.AUTH_USER_MODEL)),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_valides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('abonnement__isnull', False), ('achat_pack__isnull', True)), models.Q(('abonnement__isnull', True), ('achat_pack__isnull', False)), _connector='OR'), name='paiement_abonnement_ou_pack_exclusif')],
            },
        ),
    ]
