# Generated by Django 5.1.15 on 2026-08-26 16:31

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='preuve_paiement',
            field=models.ImageField(blank=True, help_text="Capture d'écran de la confirmation de paiement (Mobile Money ou reçu).", null=True, upload_to='paiements/preuves/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), core.validators.valider_taille_image, core.validators.valider_contenu_image]),
        ),
    ]
