# Generated by Django 6.1 on 2026-08-08 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('qcm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RemunerationCreateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode_debut', models.DateField()),
                ('periode_fin', models.DateField()),
                ('nb_questions_produites', models.PositiveIntegerField()),
                ('montant_calcule', models.DecimalField(decimal_places=2, max_digits=10)),
                ('devise', models.CharField(default='XOF', max_length=10)),
                ('statut', models.CharField(choices=[('calculee', 'Calculée (en attente de paiement)'), ('payee', 'Payée')], default='calculee', max_length=20)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('profil_createur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remunerations', to='core.profilcreateur')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remunerations_validees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionRemuneree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qcm.question')),
                ('remuneration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_incluses', to='remuneration.remunerationcreateur')),
            ],
            options={
                'unique_together': {('remuneration', 'question')},
            },
        ),
    ]
