# Generated by Django 6.1 on 2026-08-08 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qcm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tentative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('corrigee_auto', 'Corrigée automatiquement'), ('attente_correction', 'En attente de correction manuelle'), ('corrigee_complete', 'Corrigée complètement')], default='en_cours', max_length=20)),
                ('score_obtenu', models.FloatField(blank=True, null=True)),
                ('score_max', models.FloatField(blank=True, null=True)),
                ('qcm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentatives', to='qcm.qcm')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentatives', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReponseUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte_saisi', models.TextField(blank=True)),
                ('points_attribues', models.FloatField(blank=True, null=True)),
                ('date_correction', models.DateTimeField(blank=True, null=True)),
                ('corrige_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections_effectuees', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qcm.question')),
                ('reponses_choisies', models.ManyToManyField(blank=True, to='qcm.reponse')),
                ('tentative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses_utilisateur', to='tentatives.tentative')),
            ],
        ),
    ]
