# Generated by Django 6.1 on 2026-08-08 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanAbonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type_cible', models.CharField(choices=[('organisation', 'Organisation'), ('individuel', 'Utilisateur individuel')], max_length=20)),
                ('duree', models.CharField(choices=[('mensuel', 'Mensuel'), ('trimestriel', 'Trimestriel'), ('annuel', 'Annuel')], max_length=20)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('devise', models.CharField(default='XOF', max_length=10)),
                ('nb_qcm_max', models.PositiveIntegerField(blank=True, help_text='null = illimité', null=True)),
                ('nb_utilisateurs_max', models.PositiveIntegerField(blank=True, help_text='null = illimité', null=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('expire', 'Expiré'), ('annule', 'Annulé'), ('en_attente', 'En attente de paiement')], default='en_attente', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to='core.organisation')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abonnements', to='abonnements.planabonnement')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('organisation__isnull', False), ('utilisateur__isnull', True)), models.Q(('organisation__isnull', True), ('utilisateur__isnull', False)), _connector='OR'), name='abonnement_org_ou_utilisateur_exclusif')],
            },
        ),
    ]
