# Generated by Django 5.1.15 on 2026-08-10 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonnements', '0001_initial'),
        ('qcm', '0002_qcm_penalise_erreurs_choix_multiple'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('devise', models.CharField(default='XOF', max_length=10)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('thematique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packs', to='qcm.thematique')),
            ],
        ),
        migrations.CreateModel(
            name='AchatPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de paiement'), ('actif', 'Actif')], default='en_attente', max_length=20)),
                ('date_achat', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achats_packs', to=settings.AUTH_USER_MODEL)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='achats', to='abonnements.pack')),
            ],
            options={
                'unique_together': {('utilisateur', 'pack')},
            },
        ),
    ]
